Pia 2938 Update analysis screen
gini/gini-mobile-ios pull request #131
Opened 2022-08-22 11:57 UTC by vizaknaidavid

![Simulator Screen Shot - iPhone 13 Pro - 2022-08-22 at 14 56 52](https://user-images.githubusercontent.com/19169669/185915756-338e686e-f699-417e-9bcb-09f8c68740f8.png)

![Simulator Screen Shot - iPhone 13 Pro - 2022-08-22 at 14 57 26](https://user-images.githubusercontent.com/19169669/185915790-19dd43e2-1186-4c7c-9f65-16d8fdf4baf7.png)

2022-08-22 13:36 UTC, zladzeyka commented on CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Analysis/AnalysisViewController.swift
>      public override func loadView() {
we need to remove `loadView()` explanation is here https://developer.apple.com/documentation/uikit/uiviewcontroller/1621454-loadview

2022-08-22 13:55 UTC, zladzeyka commented on BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/GiniBankConfiguration.swift
> +    @objc public var analysisLoadingIndicatorColor = UIColor.from(giniColor: GiniColor(lightModeColor: .black, darkModeColor: .white))
Please pick the color from GiniColors.xcassets

2022-08-22 13:59 UTC, zladzeyka commented on CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Helpers/Localization/String Resources/AnalysisStrings.swift
>      suggestion1Details, suggestion2Details, suggestion3Details, suggestion4Details, suggestion5Details
Could you please change the way for our localization:
        title = NSLocalizedStringPreferredFormat(
            "ginicapture.help.supportedFormats.title",
            comment: "Supported formats screen title")

2022-08-22 14:04 UTC, zladzeyka commented on CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Analysis/AnalysisViewController.swift
> +        loadingIndicatorView.color = giniConfiguration.analysisLoadingIndicatorColor
The color will be from GiniColors pallete

2022-08-22 14:08 UTC, zladzeyka commented on CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Analysis/CaptureSuggestionsView.swift
> +        suggestionTextTitle.font = font.with(weight: .bold, size: 16, style: .body)
Please, use font in such way:
        cell.headerLabel.font = giniConfiguration.textStyleFonts[.headline]

2022-08-22 14:21 UTC, zladzeyka commented on CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Analysis/CaptureSuggestionsView.swift
> +                                                      toItem: self, attribute: .top, multiplier: 1,
We've agreed to do the maximum constraints in xib 😉

2022-08-22 14:24 UTC, zladzeyka requested changes
@vizaknaidavid Great progress 😉👍🏻🎉
For this PR you can add xib and remove the coding constraints where it's possible to do so. Other comments related more to the customization.

2022-08-23 12:09 UTC, vizaknaidavid commented
@zladzeyka Addressed all comments, except the color ones, I will fix those in the next PR.

2022-08-24 14:10 UTC, vizaknaidavid commented on BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/GiniBankConfiguration.swift
> +    @objc public var analysisLoadingIndicatorColor = UIColor.from(giniColor: GiniColor(lightModeColor: .black, darkModeColor: .white))
Needs to be changed

2022-08-24 14:10 UTC, vizaknaidavid commented on CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Analysis/AnalysisViewController.swift
> +        loadingText.textColor = UIColor.from(giniColor: GiniColor(lightModeColor: .black, darkModeColor: .white))
Change this to assets

2022-08-24 14:10 UTC, vizaknaidavid commented on CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Analysis/AnalysisViewController.swift
> +        overlayView.backgroundColor = UIColor.from(giniColor: GiniColor(lightModeColor: .white, darkModeColor: .black)).withAlphaComponent(0.6)
Use color from asset

2022-08-24 14:10 UTC, vizaknaidavid commented on CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Analysis/AnalysisViewController.swift
> +        view.backgroundColor = UIColor.from(giniColor: GiniColor(lightModeColor: .white, darkModeColor: .black))
Use color from asset

2022-08-26 08:46 UTC, zladzeyka commented
![Simulator Screen Shot - iPhone 6 - 2022-08-26 at 10 42 36](https://user-images.githubusercontent.com/3911816/186863618-2e6df75e-566e-4dea-a3e0-8c7f628500dc.png)
Some insets are missing iOS 12 iPhone 6 😊

2022-08-26 08:52 UTC, chriskryn requested changes
@vizaknaidavid Could you add the files you edited into swift lint configuration file at CaptureSDK/GiniCaptureSDKExample/.swiftlint.yml and fix the warnings within these files?

2022-08-26 10:15 UTC, chriskryn requested changes
![Simulator Screen Shot - iPhone SE (3rd generation) - 2022-08-26 at 12 12 21](https://user-images.githubusercontent.com/1632312/186882378-caf28473-b1be-48f4-b79d-854ce75653fb.png)
It seems there is a problem with bottom constraint and safe area

2022-08-26 10:15 UTC, chriskryn commented on CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Analysis/AnalysisViewController.swift
>      fileprivate lazy var loadingIndicatorText: UILabel = {
@vizaknaidavid Could you use private instead of fileprivate whenever it's not necessary?

2022-08-26 10:33 UTC, vizaknaidavid commented on BankSDK/GiniBankSDKExample/GiniBankSDKExampleBank/PaymentViewController.swift
> +                    self?.view.showLoading(style: .whiteLarge, color: UIColor.white, scale: 1.0)
This loading indicator is just part of the example project, not the SDK itself, in order to be able to use the color from the Gini palette, we would need to make all the colors public, and we agreed not to do that.

2022-08-26 10:33 UTC, vizaknaidavid commented on BankSDK/GiniBankSDKPinningExample/GiniBankSDKExampleBank/PaymentViewController.swift
> +                    self?.view.showLoading(style: .whiteLarge, color: UIColor.white, scale: 1.0)
Same here

2022-08-26 10:34 UTC, vizaknaidavid commented on CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Helpers/Localization/String Resources/AnalysisStrings.swift
> +
Yes, I got that info right after I committed this change. I am not using the cases anywhere.

2022-08-26 10:37 UTC, zladzeyka commented on BankSDK/GiniBankSDKExample/GiniBankSDKExampleBank/PaymentViewController.swift
> +                    self?.view.showLoading(style: .whiteLarge, color: UIColor.white, scale: 1.0)
we can leave with it

2022-08-26 10:38 UTC, zladzeyka commented on BankSDK/GiniBankSDKPinningExample/GiniBankSDKExampleBank/PaymentViewController.swift
> +                    self?.view.showLoading(style: .whiteLarge, color: UIColor.white, scale: 1.0)
we can leave with it

2022-08-26 11:02 UTC, zladzeyka requested changes
@vizaknaidavid Thank you for your work 🎉👏🏻😊
I've found a small design inconsistency:
Result
![Simulator Screen Shot - iPad Pro (11-inch) (3rd generation) - 2022-08-26 at 12 58 47](https://user-images.githubusercontent.com/3911816/186889899-e17083bf-cc49-480f-8eb5-b26e43b39b14.png)
Expectation please add a hint view background color:
<img width="430" alt="Screenshot 2022-08-26 at 09 51 55" src="https://user-images.githubusercontent.com/3911816/186890087-0faeee07-1ae9-4f01-baba-fbe8688b0de8.png">

2022-08-26 11:49 UTC, zladzeyka commented on CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Helpers/Localization/String Resources/AnalysisStrings.swift
> +
if it's not used - remove it 🎉

2022-08-26 13:04 UTC, vizaknaidavid commented
> @vizaknaidavid Thank you for your work 🎉👏🏻😊
> I've found a small design inconsistency:
> Result
> ![Simulator Screen Shot - iPad Pro (11-inch) (3rd generation) - 2022-08-26 at 12 58 47](https://user-images.githubusercontent.com/3911816/186889899-e17083bf-cc49-480f-8eb5-b26e43b39b14.png)
> Expectation please add a hint view background color:
> <img alt="Screenshot 2022-08-26 at 09 51 55" width="430" src="https://user-images.githubusercontent.com/3911816/186890087-0faeee07-1ae9-4f01-baba-fbe8688b0de8.png">

With the current color setup it is not possible to correct it. Waiting for Istvan to fix the assets

2022-08-26 13:07 UTC, zladzeyka approved these changes
We've agreed with @vizaknaidavid about the same color as a background for the capture suggestion view (tip). I'll address this issue.

2022-08-26 14:33 UTC, merged