Accessibility requirements on the analysis screen
gini/gini-mobile-ios pull request #138
Opened 2022-08-31 07:27 UTC by vizaknaidavid

feat(GiniCaptureSDK) Add accesibility requirments for image, title and description

2022-09-01 12:33 UTC, zladzeyka commented on CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Analysis/CaptureSuggestionsView.swift
> +
```suggestion
- 
```

2022-09-01 12:35 UTC, zladzeyka commented on CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Analysis/CaptureSuggestionsViewContainer.swift
> +        isAccessibilityElement = false
@vizaknaidavid would you mind accessibility-related code in a separate method to `configure Accessibility()` ?

2022-09-01 12:36 UTC, zladzeyka requested changes
Great work and a few changes are left 😊

2022-09-01 15:35 UTC, chriskryn requested changes
<img width="826" alt="Screenshot 2022-09-01 at 17 02 50" src="https://user-images.githubusercontent.com/1632312/187954262-32b96205-36d2-49a5-bf58-6272d96e650d.png"> There seems to be some hidden label, Could you tell me what's the purpose of it?

CaptureSuggestionsView contains some linters waringins could you fix them?
Also, fielprivate keyword seems to be not necessary within CaptureSuggestionsViewContainer

2022-09-01 15:35 UTC, chriskryn commented on CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Analysis/CaptureSuggestionsViewContainer.swift
> +    private var accessibilityImageDescription: String? {
Not sure If there is a need of having this variable ?

2022-09-01 15:35 UTC, chriskryn commented on CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Analysis/CaptureSuggestionsViewContainer.swift
> +        self.titleLabel.accessibilityValue = title
I think there is no need to have accessibilityValue for labels. Then the text is read twice

2022-09-01 15:51 UTC, chriskryn requested changes
@vizaknaidavid Could you center the loader and the text like in the designs?
<img width="248" alt="Screenshot 2022-09-01 at 17 50 35" src="https://user-images.githubusercontent.com/1632312/187957970-b983f664-31e2-41d3-9350-6846a9709265.png">

2022-09-02 12:04 UTC, chriskryn requested changes
I spotted that hideAnimation and showAnimation in AnalysisViewController are not used anywhere. Should we remove it? Beside that it looks good to me :+1:

2022-09-02 12:31 UTC, vizaknaidavid commented
> I spotted that hideAnimation and showAnimation in AnalysisViewController are not used anywhere. Should we remove it? Beside that it looks good to me 👍

It is a public function, and I think it could be called from the outside, si that's why I didn't touch it.

2022-09-02 12:46 UTC, chriskryn approved these changes
:+1:

2022-09-02 12:54 UTC, zladzeyka commented on CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Analysis/CaptureSuggestionsViewContainer.swift
> +        configureAccessability()
A small typo Accessability-> Accessibility🙈

2022-09-02 12:55 UTC, zladzeyka requested changes
Great job, only a small typo to fix 😊

2022-09-02 13:12 UTC, zladzeyka approved these changes
👏🏻🎉👍🏻

2022-09-08 11:54 UTC, merged