fix(GiniCaptureSDK): fix flash button aligmnent
gini/gini-mobile-ios pull request #173
Opened 2022-10-25 10:35 UTC by chriskryn

PIA-3208

2022-10-25 13:36 UTC, zladzeyka requested changes
Looks good when all configuration options are switched on:
- when flash is disabled (could you please check with Anne if it's ok)
![IMG_305457118343-1](https://user-images.githubusercontent.com/3911816/197786817-96b15a67-38ec-4e7c-ac89-382f036b140b.jpeg)
- when the import is disabled the import button should be hidden, but it's still presented.

https://user-images.githubusercontent.com/3911816/197787969-31d0eae1-15b4-4c44-a759-7234071883e1.MP4

2022-10-27 13:54 UTC, vizaknaidavid commented on CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Camera/Views/CameraPane.swift
> +        if flashButton.isHidden == false {
[Suggestion] `if !flashButton.isHidden`

2022-10-27 13:54 UTC, vizaknaidavid commented on CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Camera/Views/CameraPane.swift
> +        var number = 2
[Suggestion] Maybe it is rocket science, but: `[flashButton.isHidden, fileUploadButton.isHidden].filter({$0}).count`

2022-10-27 13:54 UTC, vizaknaidavid commented on CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Camera/Views/CameraPane.swift
> +    ) {
Is this newline needed here?

2022-11-02 17:55 UTC, zladzeyka approved these changes
Looks good 😊👏🏻🎉

2022-11-03 14:03 UTC, vizaknaidavid approved these changes

2022-11-08 13:13 UTC, zladzeyka requested changes
![IMG_0020](https://user-images.githubusercontent.com/3911816/200573711-0a06025c-6efd-4678-80f8-be809d9f7742.PNG)
There's a tiny issue on the iPad with a landscape orientation. 🥲

2022-11-08 15:50 UTC, zladzeyka approved these changes
Looks good!

2022-11-09 13:17 UTC, merged