Pia 3199 no result updates
gini/gini-mobile-ios pull request #179
Opened 2022-11-07 18:18 UTC by chriskryn

Update display of buttons within no result screen

2022-11-08 08:29 UTC, vizaknaidavid requested changes

2022-11-08 08:29 UTC, vizaknaidavid commented on CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/NoResult/NoResultScreenViewController.swift
> +            viewModel.isEnterManuallyHidden() == false,
[Suggestion] viewModel.isEnterManuallyHidden() is already a Boolean, it should not be compared to false.

2022-11-08 08:29 UTC, vizaknaidavid commented on CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/NoResult/NoResultScreenViewController.swift
> +            $0 == true
Same

2022-11-08 08:29 UTC, vizaknaidavid commented on CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/NoResult/NoResultScreenViewController.swift
> +                bottom: buttonsView.bounds.size.height + CGFloat(numberOfButtons) * GiniMargins.margin,
[Suggestion] I think the `numberOfButtons` can be declared as CGFloat from the start

2022-11-08 08:29 UTC, vizaknaidavid commented on CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/NoResult/NoResultScreenViewController.swift
> +            return 50
You should use the constants declared below

2022-11-08 14:43 UTC, zladzeyka requested changes
https://user-images.githubusercontent.com/3911816/200593693-13965d85-3731-4a0a-a05d-f82d751ad1e6.MP4
@chriskryn would you mind to check this issue, looks like the old images are retained 🥲

2022-11-08 14:43 UTC, zladzeyka commented on CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/NoResult/NoResultScreenViewController.swift
> +            return Constants.twoBUttonsHeight.rawValue
[Suggestion] a little typo twoBUttonsHeight -> twoButtonsHeight 😉

2022-11-08 14:43 UTC, zladzeyka commented on CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/NoResult/NoResultScreenViewController.swift
> +        enterButton.addBlurEffect(cornerRadius: 14)
[Suggestion] it makes sense to reuse _outlineButtonCornerRadius_ from _GiniConfiguration_.

2022-11-08 17:31 UTC, zladzeyka approved these changes
@chriskryn Great job!😊
I'll need your input on the documentation.

2022-11-10 10:22 UTC, vizaknaidavid approved these changes
Looks good

2022-11-10 16:41 UTC, zladzeyka approved these changes
Looks good!

2022-11-10 19:34 UTC, merged