Pia 3327 error screen
gini/gini-mobile-ios pull request #195
Opened 2022-11-22 23:01 UTC by chriskryn

2022-11-23 17:11 UTC, zladzeyka requested changes
Great job 👏🏻

I only have a few small sugesstions 😊

2022-11-23 17:11 UTC, zladzeyka commented on CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Error/ErrorScreenViewController.swift
> +        errorHeader.backgroundColor = GiniColor(
[Suggestion] can we move "errorHeader.backgroundColor" up for having all _errorHeader_ configurations together?

2022-11-24 11:21 UTC, chriskryn commented on CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Error/ErrorScreenViewController.swift
> +    private func configureCustomTopNavigationBar() {
@zladzeyka it's the same method we have in no result screen, currently it doesn't include bottom navigation bar nor top.  But, I think we will add it here. I have added TODO to clarify.

2022-11-24 11:32 UTC, vizaknaidavid reviewed
Just one small suggestion, looks good :D

2022-11-24 11:32 UTC, vizaknaidavid commented on CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Error/ErrorScreenViewController.swift
> +        errorContent.textAlignment = .left
The UILabel's textalignment is .left by default. If you need it somehow, I would put it in the initializer of the view

2022-11-24 11:51 UTC, chriskryn commented on CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Error/ErrorScreenViewController.swift
> +                comment: "Enter manually"))
@zladzeyka I replaced bottoms view with custom implementation. Currently, it's used in both ErrorScreen and NoResultScreen. Each screen has its own translation

2022-11-24 12:41 UTC, zladzeyka commented on CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Error/ErrorScreenViewController.swift
> +                comment: "Enter manually"))
My bad.. I meant to update the comment: "Enter manually" was used twice.
```
   secondTitle: NSLocalizedStringPreferredFormat(
                "ginicapture.error.backToCamera",
                comment: "Enter manually"))
```

2022-11-24 12:43 UTC, zladzeyka commented on CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Error/ErrorScreenViewController.swift
> +                comment: "Enter manually"))
```suggestion
                comment: "Back to camera"))
```

2022-11-24 12:45 UTC, zladzeyka approved these changes
@chriskryn  Looks good.
I've added a tiny suggestion, feel free to commit it. 😊

2022-11-30 09:26 UTC, zladzeyka approved these changes
👏🏻

2022-12-01 10:10 UTC, merged