chores: Fix swiftlint warnings
gini/gini-mobile-ios pull request #363
Opened 2023-05-08 14:26 UTC by ValentinaIancu-Gini

chores: Fix swiftlint warnings
- added enable rule for the ones that were missing after disabling them 

Remains to fix other two warnings:
`// swiftlint:disable force_cast` - we can discuss later
`// swiftlint:disable implicit_getter` - I have a suggestion to fix this

2023-05-08 15:50 UTC, zladzeyka requested changes
Great job 👏🏻,
I've added only a few tiny suggestions for the consistency of the `swiftlint` comments

2023-05-08 15:50 UTC, zladzeyka commented on CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/GiniConfiguration.swift
> +    // swiftlint: disable function_parameter_count
To keep the consistent style of the `swiftlint` messages - no space or shall we add a space after the colon
```suggestion
    // swiftlint:disable function_parameter_count
```

2023-05-08 15:50 UTC, zladzeyka commented on CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/GiniConfiguration.swift
> +    // swiftlint: enable function_parameter_count
```suggestion
    // swiftlint:enable function_parameter_count
```

2023-05-08 15:50 UTC, zladzeyka commented on CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Camera/Camera2/CameraLensSwitcherView.swift
> +// swiftlint: enable type_body_length
```suggestion
// swiftlint:enable type_body_length
```

2023-05-09 07:14 UTC, ValentinaIancu-Gini commented
> Great job 👏🏻, I've added only a few tiny suggestions for the consistency of the `swiftlint` comments

Thanks. I fixed them.

2023-05-09 10:01 UTC, zladzeyka approved these changes

2023-05-09 10:01 UTC, zladzeyka commented on CaptureSDK/GiniCaptureSDK/Sources/GiniCaptureSDK/Core/Screens/Camera/Camera2/CameraLensSwitcherView.swift
> +// swiftlint:enable  type_body_length
```suggestion
// swiftlint:enable type_body_length
```

2023-05-10 12:53 UTC, merged