Pia 4098 drag to dismiss edit article modal screen UI layout issues
gini/gini-mobile-ios pull request #386
Opened 2023-07-06 11:10 UTC by ValentinaIancu-Gini

2023-07-06 11:22 UTC, ValentinaIancu-Gini commented on BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/ReturnAssistant/EditLineItem/EditLineItemView.swift
> +		stackView.distribution = .fill
Please ignore this indentation, it's github issue :(

2023-07-10 17:01 UTC, zladzeyka requested changes
Great job,
I've left a few tiny questions ☺️

2023-07-10 17:01 UTC, zladzeyka commented on BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/UIView+RoundCorners.swift
> +		layer.masksToBounds = radius != 0
Clarification: how should we read this?
		`layer.masksToBounds = radius != 0`
And why we don't need `!=0` for
		`layer.cornerRadius = radius`

2023-07-11 15:16 UTC, zladzeyka commented
https://github.com/gini/gini-mobile-ios/assets/3911816/544fbd4b-162e-4d22-806e-8c171ab057c7

I've noticed one small layout issue if we rotate the screen and drag the presented screen up a bit, the screen will not update layout and going under the keyboard

2023-07-17 09:16 UTC, zladzeyka approved these changes

2023-07-17 09:17 UTC, zladzeyka commented
> > RPReplay_Final1689088402.MP4
> > I've noticed one small layout issue if we rotate the screen and drag the presented screen up a bit, the screen will not update layout and going under the keyboard
> 
> Related to this, this is not something affected by these current changes :|. I've tested on the main branch and is also happening.
> 
>  Simulator.Screen.Recording.-.iPad.Air.2.-.2023-07-11.at.18.00.43.mp4 
> 
> Do you want me to fix it in my pr? Or should we create a separate ticket for this?

It will be a separate ticket

2023-07-17 11:48 UTC, merged

2023-07-18 13:08 UTC, ValentinaIancu-Gini commented
> > > RPReplay_Final1689088402.MP4
> > > I've noticed one small layout issue if we rotate the screen and drag the presented screen up a bit, the screen will not update layout and going under the keyboard
> > 
> > 
> > Related to this, this is not something affected by these current changes :|. I've tested on the main branch and is also happening.
> > Simulator.Screen.Recording.-.iPad.Air.2.-.2023-07-11.at.18.00.43.mp4
> > Do you want me to fix it in my pr? Or should we create a separate ticket for this?
> 
> It will be a separate ticket

I will create a ticket for this!