feat(GiniHealthSDK): Onboarding Open with bottom sheet + PDF sharing IPC-246
gini/gini-mobile-ios pull request #498
Opened 2024-05-09 09:28 UTC by razvancapra

[IPC-246](https://ginis.atlassian.net/browse/IPC-246)

UI for onboarding OpenWith + 2 mocked payment provders for testing till backend is ready.

2024-05-15 17:53 UTC, zladzeyka requested changes
Great job 🥳,
there a couple of refactoring suggestions and I will need your help to test it tomorrow 🙏

2024-05-15 17:53 UTC, zladzeyka commented on HealthSDK/GiniHealthSDK/Sources/GiniHealthSDK/Resources/de.lproj/Localizable.strings
>  "ginihealth.paymentcomponent.installAppBottom.notes.description" = "Hinweis: Bitte aktualisieren oder installieren Sie zunächst die [BANK]-App aus dem App-Store.";
[Suggestion]: @razvancapra  could you please add `sheet` to the keys `ginihealth.paymentcomponent.installAppBottom` -> `ginihealth.paymentcomponent.installAppBottomSheet`

2024-05-15 17:53 UTC, zladzeyka commented on HealthSDK/GiniHealthSDK/Sources/GiniHealthSDK/Resources/de.lproj/Localizable.strings
> +"ginihealth.paymentcomponent.shareInvoiceBottom.title" = "Rechnungsdaten bereit zum Teilen mit der [BANK]";
[Suggestion]: @razvancapra could you please add sheet to the keys `ginihealth.paymentcomponent.shareInvoiceBottom` -> `ginihealth.paymentcomponent.shareInvoiceBottomSheet`

2024-05-15 17:53 UTC, zladzeyka commented on HealthSDK/GiniHealthSDK/Sources/GiniHealthSDK/Core/PaymentReviewViewController.swift
>  extension PaymentReviewViewController: PaymentReviewViewModelDelegate {
[Suggestion]: the vc is getting very big let's refactor it as 1st step extract the extension in separate files

2024-05-15 17:53 UTC, zladzeyka commented on HealthSDK/GiniHealthSDK/Sources/GiniHealthSDK/Core/PaymentComponent/ShareInvoiceBottomView.swift
> +    private lazy var titleView: UIView = {
[Suggestion]: could you please extract a shared code from `titleView` and `tipView`?

2024-05-15 17:53 UTC, zladzeyka commented on HealthSDK/GiniHealthSDK/Sources/GiniHealthSDK/Core/PaymentComponent/ShareInvoiceBottomView.swift
> +class SingleAppView: UIView {
[Suggestion]: Could you please extract `SingleAppView` class to a dedicated file?

2024-05-17 15:18 UTC, zladzeyka reviewed
Thank you @razvancapra 
a couple of tiny things and can we remove `internal` access level?

2024-05-17 15:18 UTC, zladzeyka commented on HealthSDK/GiniHealthSDK/Sources/GiniHealthSDK/Core/PaymentReviewViewController+UICollection.swift
> +    // MARK: - UICollectionViewDelegateFlowLayout
```suggestion

    // MARK: - UICollectionViewDelegateFlowLayout
```

2024-05-17 15:18 UTC, zladzeyka commented on HealthSDK/GiniHealthSDK/Sources/GiniHealthSDK/Core/PaymentReviewViewController+UITextFieldDelegate.swift
> +    internal func updateAmoutToPayWithCurrencyFormat() {
```suggestion
    func updateAmoutToPayWithCurrencyFormat() {
```

2024-05-17 15:38 UTC, razvancapra commented on HealthSDK/GiniHealthSDK/Sources/GiniHealthSDK/Core/PaymentComponent/BottomSheetViewController.swift
> +            guard let self = self else { return }
Not needed.

2024-05-17 15:55 UTC, zladzeyka approved these changes
Thanks 🙏

2024-05-20 07:59 UTC, merged