feat(GiniHealthSDK): Download pdf API v4
gini/gini-mobile-ios pull request #515
Opened 2024-06-05 09:52 UTC by razvancapra

Tasks included:
https://ginis.atlassian.net/browse/IPC-252
https://ginis.atlassian.net/browse/IPC-267
https://ginis.atlassian.net/browse/IPC-259

2024-06-05 13:12 UTC, zladzeyka requested changes
👏🏻 Great job @razvancapra 
there're a couple of suggestion. I will continue with testing the PR

2024-06-05 13:12 UTC, zladzeyka commented on HealthAPILibrary/GiniHealthAPILibrary/Sources/GiniHealthAPILibrary/Documents/APIResource.swift
>          case .gym: return 2
[Request]: @razvancapra we need to remove `gym` from `HealthAPILibrary` and `HealthSDK` resources

2024-06-06 06:54 UTC, razvancapra commented on HealthSDK/GiniHealthSDK/Sources/GiniHealthSDK/Core/PaymentComponent/PaymentComponentViewModel.swift
> +    let giniHealthConfiguration: GiniHealthConfiguration
I got some memory warnings into previous implementation due to the high number of cells that where getting instantiated while quick scrolling. I decided to inject the configuration in there.

2024-06-06 07:03 UTC, razvancapra commented on HealthSDK/GiniHealthSDK/Sources/GiniHealthSDK/Resources/GiniImages.xcassets/more_vertical.imageset/more-vertical (1).pdf
Yes. We do need. One of them is for Dark more, the other one is for light mode.

2024-06-06 13:45 UTC, merged