EC-63 repack Health SDK into Merchant SDK
gini/gini-mobile-ios pull request #543
Opened 2024-06-21 11:33 UTC by motokotomax

2024-06-24 17:17 UTC, zladzeyka approved these changes

2024-06-26 15:51 UTC, zladzeyka requested changes
@motokotomax could you please look at [Sonar](https://sonarcloud.io/project/issues?id=gini_gini-mobile-ios&pullRequest=543&resolved=false&sinceLeakPeriod=true) cloud issues?

2024-06-26 17:12 UTC, motokotomax commented on MerchantSDK/GiniMerchantSDK/Documentation/source/Installation.md
> +    .package(url: "https://github.com/gini/merchant-sdk-pinning-ios.git", .exact("4.1.0"))
fixed

2024-06-26 17:12 UTC, motokotomax commented on MerchantSDK/GiniMerchantSDK/Package-release.swift
> +            dependencies: ["GiniHealthSDK"]),
fixed

2024-06-26 17:12 UTC, motokotomax commented on MerchantSDK/GiniMerchantSDK/Package-release.swift
> +    platforms: [.iOS(.v12)],
fixed

2024-06-26 17:13 UTC, motokotomax commented on HealthSDK/GiniHealthSDK/GiniHealth_Logo.png
thanks, yes you right - recover icon

2024-06-28 08:33 UTC, zladzeyka approved these changes

2024-07-01 11:54 UTC, zladzeyka approved these changes
👍🏻

2024-07-11 12:55 UTC, merged