Ec 63 update merchant sdk api
gini/gini-mobile-ios pull request #550
Opened 2024-06-26 08:51 UTC by motokotomax

Hide HealthSDK API from client app

2024-06-28 16:24 UTC, zladzeyka requested changes
Thank you @motokotomax 👏🏻
Please find a couple of comments 😊
I think it's time to create the GitHub workflows for Merchant 😉

2024-06-28 16:24 UTC, zladzeyka commented on MerchantSDK/GiniMerchantSDK/Sources/GiniMerchantSDK/Core/Adapter/Mapping.swift
> +        let gpcPlatforms = healthPaymentProvider.gpcSupportedPlatforms.compactMap { PlatformSupported(rawValue: $0.rawValue) }
```suggestion
        let gpcSupportedPlatforms = healthPaymentProvider.gpcSupportedPlatforms.compactMap { PlatformSupported(rawValue: $0.rawValue) }
```

2024-06-28 16:24 UTC, zladzeyka commented on MerchantSDK/GiniMerchantSDK/Sources/GiniMerchantSDK/Core/Adapter/Mapping.swift
> +        let minAppVersions: MinAppVersions?
[Suggestion]: it's not used anywhere I think we can skip `MinAppVersions`

2024-06-28 16:24 UTC, zladzeyka commented on MerchantSDK/GiniMerchantSDK/Sources/GiniMerchantSDK/Core/GiniMerchant+Test.swift
> +//  File.swift
``` suggestion
//  GiniMerchant + Test.swift
```

2024-06-28 16:24 UTC, zladzeyka commented on MerchantSDK/GiniMerchantSDK/Sources/GiniMerchantSDK/Core/GiniMerchant+Test.swift
> +@testable import GiniHealthAPILibrary
[Clarification]: Shall we move it to tests?

2024-06-28 16:24 UTC, zladzeyka commented on MerchantSDK/GiniMerchantSDK/Tests/GiniMerchantSDKTests/MockHelpers/Utils.swift
> +        let gpcPlatforms = providerResponse.gpcSupportedPlatforms.compactMap { GiniMerchantSDK.PlatformSupported(rawValue: $0.rawValue) }
```suggestion
        let gpcSupportedPlatforms = providerResponse.gpcSupportedPlatforms.compactMap { GiniMerchantSDK.PlatformSupported(rawValue: $0.rawValue) }
```

2024-06-28 16:24 UTC, zladzeyka commented on MerchantSDK/GiniMerchantSDK/Tests/GiniMerchantSDKTests/MockHelpers/Utils.swift
> +        let openPlatforms = providerResponse.openWithSupportedPlatforms.compactMap { GiniMerchantSDK.PlatformSupported(rawValue: $0.rawValue) }
```suggestion
        let openWithPlatforms = providerResponse.openWithSupportedPlatforms.compactMap { GiniMerchantSDK.PlatformSupported(rawValue: $0.rawValue) }
```

2024-07-01 10:45 UTC, motokotomax commented
@zladzeyka  thanks for review!
issues fixed

2024-07-01 13:13 UTC, zladzeyka requested changes
@motokotomax  thank you for the fixes 2 more small notes :)

2024-07-02 09:51 UTC, zladzeyka approved these changes
👏🏻

2024-07-02 16:51 UTC, merged