feat(HealthSDK) Add force set for Health SDK language
gini/gini-mobile-ios pull request #554
Opened 2024-07-01 07:15 UTC by motokotomax

2024-07-02 09:57 UTC, zladzeyka requested changes

2024-07-02 13:21 UTC, motokotomax commented
Thanks @zladzeyka for review, fix applied

2024-07-02 15:08 UTC, zladzeyka requested changes
🙈 sorry maybe it was a confusion from my side about the naming

2024-07-02 15:08 UTC, zladzeyka commented on HealthSDK/GiniHealthSDK/Sources/GiniHealthSDK/Core/GiniHealthConfiguration.swift
> +    public var localization: GiniLocalization?
Sorry @motokotomax  I think I've confused you here, I was proposing to call a public property `customLocalization` instead of `localization`

2024-07-02 15:08 UTC, zladzeyka commented on HealthSDK/GiniHealthSDK/Sources/GiniHealthSDK/Core/GiniLocalization.swift
> +    static func customLocalization(_ key: String, fallbackKey: String? = nil, comment: String) -> String {
```suggestion
    static func preferredLocalization(_ key: String, fallbackKey: String? = nil, comment: String) -> String {
```

2024-07-03 15:35 UTC, zladzeyka approved these changes
Great, @motokotomax could you please also check a tiny Sonar suggestion?

2024-07-03 16:57 UTC, motokotomax commented
> Great, @motokotomax could you please also check a tiny Sonar suggestion?

<img width="896" alt="Screenshot 2024-07-03 at 18 49 44" src="https://github.com/gini/gini-mobile-ios/assets/1927281/17e79dd2-0c9c-443f-8c39-d3a72bb049b1">

sonar wants constant for comment in localizable func. it's 3 different calls - not sure that it's good solution

2024-07-04 07:24 UTC, razvancapra approved these changes

2024-07-04 07:35 UTC, merged