feat(GiniMerchantSDK): Payment Review Container refactor to programatically view EC-59
gini/gini-mobile-ios pull request #558
Opened 2024-07-01 16:52 UTC by razvancapra

https://ginis.atlassian.net/browse/EC-59

We will be able to integrate it in a bottom sheet as well.

2024-07-02 07:12 UTC, motokotomax approved these changes

2024-07-02 15:40 UTC, zladzeyka requested changes
Thank you @razvancapra 
Looks good,
don't see any showstoppers just a couple of small suggestions

2024-07-02 15:40 UTC, zladzeyka commented on MerchantSDK/GiniMerchantSDK/Sources/GiniMerchantSDK/Core/PaymentReviewContainerView.swift
> +    var paymentInputFieldsErrorLabels: [UILabel] = []
[Clarification]: do the variables below should be private as well?
     var amountToPay 
     var lastValidatedIBAN 
     var paymentInputFields: 
     var paymentInputFieldsErrorLabels

2024-07-03 07:21 UTC, razvancapra commented on MerchantSDK/GiniMerchantSDK/Sources/GiniMerchantSDK/Core/PaymentReviewViewController+PaymentReviewViewModelDelegate.swift
> +        paymentInfoContainerView.noErrorsFound()
Yes. In the past we had ` func checkForErrors() {
        // check if no errors labels are shown
        if (paymentInputFieldsErrorLabels.allSatisfy { $0.isHidden }) {
            createPaymentRequest()
        }
    }`
    
We now have a function that separately checks for error and yes, there is a missing line in here, that creates the payment request. I'll fix it. Thanks

2024-07-03 07:23 UTC, razvancapra commented on MerchantSDK/GiniMerchantSDK/Sources/GiniMerchantSDK/Core/PaymentReviewContainerView.swift
> +    @discardableResult
Yes. When you don't need the result. But I've removed it, since I've fixed `paymentInfoContainerView.noErrorsFound()` from the above clarification

2024-07-08 09:52 UTC, motokotomax approved these changes
Great! 

JFYI: I changed the PR base, cause EC-63-Update-MerchantSDK-API is merged into EC-63-MerchantSDK

2024-07-08 09:52 UTC, motokotomax commented on MerchantSDK/GiniMerchantSDK/Sources/GiniMerchantSDK/Core/PaymentReviewModel.swift
> +    var onErrorHandling: (_ error: GiniMerchantError) -> Void = { _ in }
Suggestion: lets use type ((_ error: GiniMerchantError) -> Void)? - to avoid sonar issues with empty blocks and increase perfomance

2024-07-09 15:25 UTC, zladzeyka requested changes
Looks good and something got lost on the way, the error messages 🙊
https://www.figma.com/design/wBBjc38iihjxrKMnLfbOD4/iOS-Gini-Health-SDK-4.1-UI-Customisation?node-id=0-1&t=QCNAiivQEWtUWRWj-1
![Simulator Screenshot - iPhone 15 - 2024-07-09 at 17 19 57](https://github.com/gini/gini-mobile-ios/assets/3911816/5113311b-cd83-47fe-888a-40fb90de5079)

2024-07-10 07:03 UTC, razvancapra commented on MerchantSDK/GiniMerchantSDK/Sources/GiniMerchantSDK/Core/PaymentReviewViewController.swift
> +                                                    value: paymentInfoContainerView.textFieldText(texFieldType: .recipientFieldTag) ?? "",
Fixed. I forgot to update the paymentRecipientExtraction as well. 
Also, I fixed the error messages.

2024-07-11 14:36 UTC, zladzeyka requested changes
Thank you @razvancapra 
The error messages were fixed indeed. Now I've found another edge case with IBAN Validation, I think the IBAN validation should happen earlier or something else is missing, please see the video below

https://github.com/gini/gini-mobile-ios/assets/3911816/2b0a2f65-2861-48cf-ab7a-ca5a454b9e7f

2024-07-12 06:11 UTC, razvancapra commented
> Thank you @razvancapra The error messages were fixed indeed. Now I've found another edge case with IBAN Validation, I think the IBAN validation should happen earlier or something else is missing, please see the video below
> 
>  Simulator.Screen.Recording.-.iPhone.15.-.2024-07-11.at.16.33.25.mp4

Fixed. Not happening anymore.

2024-07-15 16:37 UTC, closed without merging