feat(GiniMerchantSDK): Payment initiation without invoice
gini/gini-mobile-ios pull request #595
Opened 2024-07-25 11:12 UTC by antosj

2024-07-25 15:03 UTC, razvancapra commented
Hi @antosj. Congrats on your first PR 💪 
1. Regarding UI, I suggest a few changes for start. Please check the TextViews alignments so that I can see the total text on them when entering the details. This is from the iPhone 15 Pro.
![Simulator Screenshot - iPhone 15 Pro - 2024-07-25 at 17 40 34](https://github.com/user-attachments/assets/b9ed9e38-5348-4f06-828d-87cf4bd0279c)

2. Also, I saw that in the design there are just 4 fields visible and editable: (Recipient, IBAN, Amount, and Purpose). You don't need to worry about the due date and the invoice number.  https://www.figma.com/design/e6ie7RWXbGRMIhh2pFoKQr/E-Commerce-SDK-requirements?node-id=153-1254&t=BKBk2UUZFwSTLIKm-0 `

3. I saw in the ticket that there are hardcoded data. Can you add them and replace the current one's that are coming from invoice images?

4. Not sure, but isn't Custom Order with the empty state one of the purposes of the task? Should we allow initialize any order at any time? Just double-check if needed or it's going to be implemented into the future.

5. Regarding the Pay Now flow. We need to link with the previous flow so that we can test the Payment Review Screen without an invoice (with the top part darkened). 

Ping me for anything. I'll gladly try to clarify everything.

2024-07-25 15:03 UTC, razvancapra requested changes
I left a comment with changes suggested for start.

2024-08-06 12:29 UTC, zladzeyka requested changes
Thank you for the PR @antosj 👏🏻
Please find my review notes below

2024-08-06 12:29 UTC, zladzeyka commented on MerchantSDK/GiniMerchantSDKExample/GiniMerchantSDKExample/Sources/InvoicesList/InvoiceDetailView.swift
> +        label.text = text.0
[Clarification]: Could you please help me to understand where we received the text and what's `text.0`?

2024-08-06 12:29 UTC, zladzeyka commented on MerchantSDK/GiniMerchantSDKExample/GiniMerchantSDKExample/Sources/InvoicesList/InvoiceDetailView.swift
> +        if #available(iOS 13.0, *) {
[Suggestion]: we support Merchant from iOS 13, we can skip the check

2024-08-06 12:29 UTC, zladzeyka commented on MerchantSDK/GiniMerchantSDKExample/GiniMerchantSDKExample/Sources/InvoicesList/InvoiceDetailViewController.swift
> +        if #available(iOS 13.0, *) {
[Suggestion]: iOS target for SDK and example app 13+ , we can skip the check

2024-08-06 12:29 UTC, zladzeyka commented on MerchantSDK/GiniMerchantSDKExample/GiniMerchantSDKExample/Sources/InvoicesList/InvoiceTableViewCell.swift
> +        static let amountLabelTextColor = UIColor(red: 0.0, green: 158.0 / 255.0, blue: 220.0 / 255.0, alpha: 1.0)
[Suggestion]: could you please add `amountLabelTextColor` in the app resources?

2024-08-06 12:29 UTC, zladzeyka commented on MerchantSDK/GiniMerchantSDKExample/GiniMerchantSDKExample/Sources/InvoicesList/InvoiceTableViewCellModel.swift
>      var isDueDataLabelHidden: Bool {
[Clarification]: can we remove isDueDataLabelHidden since the field was removed already?

2024-08-06 12:38 UTC, zladzeyka commented
and one small thing:
https://www.figma.com/design/e6ie7RWXbGRMIhh2pFoKQr/E-Commerce-SDK-requirements?node-id=153-1194&t=8IOUuNulnSkImZmG-1
Could you please the design:
blue color should be applied to the amount to pay field and pay button on the detailed view.

2024-08-06 15:09 UTC, zladzeyka requested changes
Looks good 👍🏻 @antosj 
Could you please also add the string as localized 🙏?

2024-08-06 15:09 UTC, zladzeyka commented on MerchantSDK/GiniMerchantSDKExample/GiniMerchantSDKExample/Sources/InvoicesList/InvoiceDetailViewController.swift
> +        button.setTitle("Pay", for: .normal)
[Suggestion]: Could you please also add "Pay" as a localized string🙏?

2024-08-06 15:09 UTC, zladzeyka commented on MerchantSDK/GiniMerchantSDKExample/GiniMerchantSDKExample/Sources/InvoicesList/InvoiceDetailViewController.swift
> +        self.title = "Order details"
[Suggestion]: Could you please also add "Order details" as a localized string🙏?

2024-08-06 15:09 UTC, zladzeyka commented on MerchantSDK/GiniMerchantSDKExample/GiniMerchantSDKExample/Sources/InvoicesList/InvoiceDetailViewController.swift
> +    case recipient = "Recipient"
[Suggestion]: Could you please the string as localized resources?

2024-08-07 07:54 UTC, zladzeyka approved these changes

2024-08-07 12:19 UTC, razvancapra approved these changes
Looks good now! Good job 👍

2024-08-19 11:50 UTC, merged