PP-208 fix "qr code detected" getting cut off
gini/gini-mobile-ios pull request #613
Opened 2024-08-05 08:28 UTC by igor-gini

I managed to replicate the issue on iPhone 6s iOS 15.8.2, but only with "QR code detected", with "Scan invoice or QR code" at the bottom everything is fine, and it already has minimumScaleFactor and adjustsFontSizeToFitWidth set up to it

2024-08-08 15:58 UTC, zladzeyka commented
![IMG_7444](https://github.com/user-attachments/assets/54ce318f-61f0-4a72-bcd5-cbd5ee82c1b4)
QR Code detected looks good! 😊

For `unknown QR` we are having issues with scaling 
![IMG_7443](https://github.com/user-attachments/assets/17366a59-15e6-47c5-b013-ebfa0bd6e949)
@igor-gini  could you please take care of it?

2024-08-12 11:52 UTC, zladzeyka requested changes
UI looks good 👏🏻
Could you please look at Sonar cloud suggestion?

2024-08-13 10:01 UTC, igor-gini commented
@zladzeyka changes done

2024-08-13 15:18 UTC, zladzeyka approved these changes
Thank you @igor-gini 
could you please prepare a build for QA?

2024-08-14 13:03 UTC, merged