Pp 623 implement full screen skonto details snapshot from the invoice
gini/gini-mobile-ios pull request #622
Opened 2024-08-12 16:43 UTC by ValentinaIancu-Gini

When the user taps that document preview view from the main screen(Skonto screen), the app should display the image of the invoice with the Skonto details highlighted in full-screen mode.

2024-08-14 11:01 UTC, mrkulik requested changes
@ValentinaIancu-Gini Great job! I left some suggestions, please let me know your thoughts!

On iPad landscape vertical scroll is not working (Image is displayed outside the frame at start and we can't scroll to the bottom/top), with horizontal all ok. Based on Figma, in landscape mode document should be displayed in full height:
https://github.com/user-attachments/assets/8fe0caca-5deb-42e1-b858-7ddde9c61629
After zooming, vertical scroll works strange, can't scroll to see image details:
https://github.com/user-attachments/assets/75320583-2c87-424d-b728-e5b82bf010ad

2024-08-14 14:47 UTC, ValentinaIancu-Gini commented on BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/Skonto/DocumentPages/DocumentPagesViewController.swift
> +        addLoadingView(intoContainer: loadingIndicatorContainer)
I think it is better to separate them because the method will be longer in the number of lines.

2024-08-14 14:48 UTC, ValentinaIancu-Gini commented on BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/Skonto/DocumentPages/DocumentPagesViewController.swift
> +        let imageViewHeight = UIScreen.main.bounds.height * 0.65
oh for iPad we have a different design ... I will fix this. Thank you!

2024-08-14 15:58 UTC, ValentinaIancu-Gini commented on BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/Skonto/DocumentPages/DocumentPagesViewController.swift
> +        scrollView.layoutIfNeeded()
we don't need.

2024-08-19 13:42 UTC, mrkulik approved these changes
@ValentinaIancu-Gini looks nice!

2024-08-19 14:20 UTC, merged