PP-711 add clientid and clientsecret credentials
gini/gini-mobile-ios pull request #628
Opened 2024-08-20 15:58 UTC by igor-gini

2024-08-27 14:23 UTC, zladzeyka requested changes
Thank you @igor-gini 👏🏻👏🏻
Could you please check the review notes?
May I ask you additionally to the review notes to look at possible refactoring of `SettingsViewController. configureTableView()`?

2024-09-03 07:06 UTC, igor-gini commented on BankSDK/GiniBankSDKExample/GiniBankSDKExample/APIEnvironment.swift
> +            return .custom(domain: "pay-api.pia.stage.gini.net")
Fixed

2024-09-03 07:06 UTC, igor-gini commented on BankSDK/GiniBankSDKExample/Tests/SettingsViewControllerTests.swift
> +        settingsViewController = SettingsViewController(apiEnvironment: .stage,
Switched to prod

2024-09-03 07:06 UTC, igor-gini commented on BankSDK/GiniBankSDKExample/Tests/ScreenAPICoordinatorTests.swift
> +        screenAPICoordinator = ScreenAPICoordinator(apiEnvironment: .stage,
Fixed

2024-09-03 07:08 UTC, igor-gini commented on BankSDK/GiniBankSDKExample/GiniBankSDKExample/SettingsViewController/SettingsViewController.swift
> +    }
Exactly, the client id and secret are applied on the save button press

2024-09-03 07:08 UTC, igor-gini commented on BankSDK/GiniBankSDKExample/GiniBankSDKExample/SettingsViewController/SettingsViewController.swift
> +        if data is FileImportSegmentedOptionModel {
Sure, separated into two methods

2024-09-03 07:08 UTC, igor-gini commented on BankSDK/GiniBankSDKExample/GiniBankSDKExample/SettingsViewController/SettingsViewController+SegmentedOptionModel.swift
>  //  Created by Valentina Iancu on 16.06.23.
Fixed

2024-09-06 15:23 UTC, zladzeyka approved these changes
Thanks @igor-gini 
I've fixed the link to the user stage API 🥹

2024-09-10 10:14 UTC, merged