PP-166 fix digital invoice line item wrong background color
gini/gini-mobile-ios pull request #640
Opened 2024-08-27 06:57 UTC by igor-gini

2024-08-27 15:26 UTC, zladzeyka approved these changes
Thank you @igor-gini 🥳
Looks nice, just a small typo in var name.

2024-08-27 15:26 UTC, zladzeyka commented on BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/ReturnAssistant/DigitalInvoice/Components/DigitalLineItemTableViewCell.swift
> +    @IBOutlet weak var backroundContainerView: UIView!
```suggestion
    @IBOutlet weak var backgroundContainerView: UIView!
```

2024-08-27 15:27 UTC, zladzeyka requested changes
Thank you @igor-gini 🥳
Looks nice, just a small typo in var name.

2024-08-30 08:39 UTC, igor-gini commented on BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/ReturnAssistant/DigitalInvoice/Components/DigitalLineItemTableViewCell.swift
> +    @IBOutlet weak var backroundContainerView: UIView!
Adjuster

2024-09-02 13:40 UTC, zladzeyka approved these changes
Thank you! 🙏 @igor-gini 
Please prepare a build for QA

2024-09-10 07:34 UTC, merged