refactor(GiniHealthAPILibrary): Remove pinning projects
gini/gini-mobile-ios pull request #651
Opened 2024-08-29 09:26 UTC by antosj

2024-09-13 12:51 UTC, zladzeyka requested changes
@antosj looks great just 2 tiny suggestions from my side

2024-09-13 12:51 UTC, zladzeyka commented on .github/workflows/health-sdk.check.yml
> -    - name: Build pinning example app and run integration tests
[Suggestion]: @antosj we need to run pinning-related tests just using the GiniHealthSDKExampleTests scheme

2024-09-23 12:42 UTC, zladzeyka requested changes
Thank you @antosj 
please check my 2 comments below

2024-09-23 12:42 UTC, zladzeyka commented on .github/workflows/health-api-library.check.yml
>          -skip-testing:GiniHealthAPILibraryPinningExampleTests/HealthAPILibraryPinningWrongCertificatesTests
```suggestion
        -skip-testing:GiniHealthAPILibraryExampleTests/HealthAPILibraryPinningWrongCertificatesTests
```

Please check what are you running here

2024-09-23 12:42 UTC, zladzeyka commented on .github/workflows/merchant-sdk.check.yml
> -        CLIENT_SECRET="${{ secrets.GINI_MOBILE_TEST_CLIENT_SECRET }}"
Please revert this change

2024-09-23 16:10 UTC, zladzeyka requested changes
Only 1 tiny suggestion

2024-09-23 16:10 UTC, zladzeyka commented on .github/workflows/health-sdk.publish.example.apps.yml
> +    uses: gini/gini-mobile-ios/.github/workflows/health-sdk.check.yml
```suggestion
    uses: ./.github/workflows/health-sdk.check.yml
```

2024-09-23 20:41 UTC, razvancapra approved these changes

2024-09-24 12:23 UTC, zladzeyka approved these changes

2024-09-24 12:32 UTC, merged