PP-802: Fix crash in storyboard
gini/gini-mobile-ios pull request #658
Opened 2024-09-05 11:40 UTC by igor-gini

The reason was that in the storyboard of that button it didn't have any custom class, just UIButton, although in the code was MultilineTitleButton, it did not crash simply because there were no additional properties before adding GiniCaptureButton.

EXC_BAD_ACCESS with code 1 usually means that the object either does not exist in memory at all (either it was never allocated or it was freed), or the address of the memory location is crooked. In this case, because the class was not defined in the storyboard (so inside uikit the memory was allocated just for UIButton), the memory for traitCollectionUpdated was not allocated, even if you put nil as default value (and Optional != nullptr).

Sometimes EXC_BAD_ACCESS also occurs because of some bugs in xcode (so far I've seen it only with v15.3.0), cleaning build folder/derived data helps in this case.

2024-09-09 13:52 UTC, zladzeyka requested changes
There is one more place to fix
<img width="1362" alt="Screenshot 2024-09-09 at 15 50 39" src="https://github.com/user-attachments/assets/35981a8e-0108-4153-8a9a-7db3a3675e58">

2024-09-10 10:16 UTC, igor-gini commented
> There is one more place to fix <img alt="Screenshot 2024-09-09 at 15 50 39" width="1362" src="https://private-user-images.githubusercontent.com/3911816/365678027-35981a8e-0108-4153-8a9a-7db3a3675e58.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU5NjM2NTEsIm5iZiI6MTcyNTk2MzM1MSwicGF0aCI6Ii8zOTExODE2LzM2NTY3ODAyNy0zNTk4MWE4ZS0wMTA4LTQxNTMtOGE5YS03ZGIzYTM2NzVlNTgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkxMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MTBUMTAxNTUxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDk2MGUzOTFjZWFjZGI4MTJmMTYwYTFiZTkwMjkzOGMxZDk3Yzc1ODBhOGJiNWZiNzE5ZjE0ZjBhMmUzYjk2OCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.6zT_zv6lzkZ3PtngVgtyW3zhAnd2iVVNAWufXIDXSaE">

This has been fixed and merged in [PP-166](https://github.com/gini/gini-mobile-ios/pull/640), I've rebased on the latest main, so this PR should have both fixes in

2024-09-10 11:03 UTC, ValentinaIancu-Gini approved these changes
@igor-gini I tested. All is good. Thank you!

2024-09-11 07:43 UTC, zladzeyka approved these changes
Thank you @igor-gini

2024-09-11 07:43 UTC, merged