IPC-322 HealthAPILibrary and HealthSDK XCFrameworks
gini/gini-mobile-ios pull request #684
Opened 2024-10-03 22:54 UTC by antosj

2024-10-10 06:48 UTC, razvancapra requested changes
Look good. 
Just a small clarification.

2024-10-10 06:48 UTC, razvancapra commented on HealthSDK/GiniHealthSDK/Sources/GiniHealthSDK/Core/GiniHealthUtils.swift
> +    Bundle.resource
Clarification: Why we need this change? 
We have down here the `giniHealthBundleResource()` function that's providing the resources.

2024-10-10 07:46 UTC, caprapaditu requested changes

2024-10-10 07:46 UTC, caprapaditu commented on HealthSDK/GiniHealthSDK/Sources/GiniHealthSDK/Core/GiniHealthUtils.swift
> +    giniHealthBundleResource()
Regarding: `giniHealthBundle()`
I would rather leave that as it is and I would use `giniHealthBundleResource()` in the `defaultImage()` function. I see there is the only place where is used.

2024-10-10 08:02 UTC, razvancapra requested changes

2024-10-10 08:02 UTC, razvancapra commented on HealthSDK/GiniHealthSDK/Sources/GiniHealthSDK/Core/GiniHealthUtils.swift
> +    giniHealthBundleResource()
Regarding: `giniHealthBundle()`
I would rather leave that as it is and I would use `giniHealthBundleResource()` in the `defaultImage()` function. I see there is the only place where is used.

2024-10-11 13:39 UTC, razvancapra approved these changes

2024-10-11 13:40 UTC, merged