Pia 2461 return assistant customisation guide
gini/gini-mobile-ios pull request #75
Opened 2022-05-02 14:13 UTC by a-szotyori

2022-05-03 10:10 UTC, zladzeyka commented on BankSDK/GiniBankSDK/Documentation/source/Customization guide.md
> +
An extra empty line.

2022-05-03 11:12 UTC, zladzeyka requested changes
Thank you! 🎉👏🏻❤️
Only one extra empty line. Please, see my comment.

2022-05-03 13:16 UTC, a-szotyori commented on BankSDK/GiniBankSDK/Documentation/source/Customization guide.md
> +
Thank you, I fixed it. 👍

2022-05-04 08:09 UTC, zladzeyka approved these changes

2022-05-04 09:22 UTC, merged