PP-777: Add Bank SDK version to upload metadata http header
gini/gini-mobile-ios pull request #753
Opened 2024-12-06 08:48 UTC by igor-gini

2025-01-09 10:59 UTC, zladzeyka requested changes
Thank you @igor-gini please find some suggestions 😇

2025-01-09 10:59 UTC, zladzeyka commented on BankAPILibrary/GiniBankAPILibrary/Sources/GiniBankAPILibrary/Documents/Document+UploadMetadata.swift
>          }
```suggestion
        }
        
```

2025-01-09 10:59 UTC, zladzeyka commented on BankAPILibrary/GiniBankAPILibrary/Sources/GiniBankAPILibrary/Documents/Document+UploadMetadata.swift
> +                .split(separator: ",").map(String.init)
[Suggestion]: AI brain provides some suggestion here: The issue lies in .split(separator: "="), which operates on each string component after splitting by ",". This chaining of splits and mapping results in a flat array of all substrings but does not correctly preserve the association between keys and values. As a result, the check for key may give false positives or negatives.
Possible solution: Use a dictionary-like approach to handle the split, ensuring keys and values remain paired.

```
// Parse existing comments into key-value pairs
    let keyValues = existingComment
        .split(separator: ",")
        .map { $0.split(separator: "=") }
        .filter { $0.count == 2 }
        .map { (String($0[0]), String($0[1])) }
    
    // Check if the key already exists
    guard !keyValues.contains(where: { $0.0 == key }) else {
        return existingComment
    }
```

2025-01-09 10:59 UTC, zladzeyka commented on BankAPILibrary/GiniBankAPILibrary/Sources/GiniBankAPILibrary/Documents/Document.swift
> +        var giniBankVersion: String?
```suggestion
        var giniBankSDKVersion: String?
```

2025-01-09 10:59 UTC, zladzeyka commented on BankAPILibrary/GiniBankAPILibrary/Sources/GiniBankAPILibrary/Documents/Document.swift
> +         * - Parameter uploadMetadata:  Upload datadata
```suggestion
         * - Parameter uploadMetadata:  Upload metadata
```

2025-01-09 10:59 UTC, zladzeyka commented on BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/GiniBankNetworkingScreenApiCoordinator.swift
> +        let docMetadata: Document.Metadata = {
[Suggestion]: Can we extract the new `documentService`code into private function to avoid duplications?

2025-01-14 09:00 UTC, igor-gini commented on BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/GiniBankNetworkingScreenApiCoordinator.swift
> +        let docMetadata: Document.Metadata = {
Added a separate function which creates Document.Metadata, DocumentService is not created the same everywhere

2025-01-14 09:00 UTC, igor-gini commented on BankAPILibrary/GiniBankAPILibrary/Sources/GiniBankAPILibrary/Documents/Document+UploadMetadata.swift
> +                .split(separator: ",").map(String.init)
добавил + сделал ещё тесты к usercomment, их не было

2025-01-14 09:01 UTC, igor-gini commented on BankAPILibrary/GiniBankAPILibrary/Sources/GiniBankAPILibrary/Documents/Document+UploadMetadata.swift
> +                .split(separator: ",").map(String.init)
Added + created tests for usercomment, there was none

2025-01-14 09:01 UTC, igor-gini commented on BankAPILibrary/GiniBankAPILibrary/Sources/GiniBankAPILibrary/Documents/Document+UploadMetadata.swift
>          }
Github doesn't show for some reason but added a new line there

2025-01-14 09:02 UTC, igor-gini commented on BankAPILibrary/GiniBankAPILibrary/Sources/GiniBankAPILibrary/Documents/Document.swift
> +        var giniBankVersion: String?
Changed this

2025-01-14 09:02 UTC, igor-gini commented on BankAPILibrary/GiniBankAPILibrary/Sources/GiniBankAPILibrary/Documents/Document.swift
> +         * - Parameter uploadMetadata:  Upload datadata
Fixed this

2025-01-17 08:55 UTC, zladzeyka requested changes

2025-01-17 08:55 UTC, zladzeyka commented on BankAPILibrary/GiniBankAPILibrary/Sources/GiniBankAPILibrary/Documents/Document.swift
>          public mutating func addUploadMetadata(_ uploadMetadata: UploadMetadata) {
[Suggestion]: This is a breaking change can we keep the old method with branchID and additional header, mark it as deprecated and introduce a new one?

2025-01-20 09:26 UTC, igor-gini commented on BankAPILibrary/GiniBankAPILibrary/Sources/GiniBankAPILibrary/Documents/Document.swift
>          public mutating func addUploadMetadata(_ uploadMetadata: UploadMetadata) {
I looked through the commit history of this file and it seems that the method with branch ID and additional methods was never present in the first place. The init, which accepts the branch id and additional headers, was always there, and is still there. The documentation for the addUploadMetadata method was wrong(and I fixed it), it likely was overlooked when the upload metadata feature was initially implemented. So short story is: docs were wrong, the method itself hasn't changed, it was like that from the beginning so no new method have been introduced, no old needs to be marked as deprecated..

2025-01-20 09:47 UTC, zladzeyka commented on BankAPILibrary/GiniBankAPILibrary/Sources/GiniBankAPILibrary/Documents/Document.swift
>          public mutating func addUploadMetadata(_ uploadMetadata: UploadMetadata) {
thank you @igor-gini

2025-01-20 09:47 UTC, zladzeyka approved these changes
Thanks @igor-gini looks good to me!

2025-01-23 11:20 UTC, ValentinaIancu-Gini approved these changes
Thanks @igor-gini looks good to me as well!

2025-02-25 09:22 UTC, merged