fix(GiniBankSDK): Expose cancel sdk function
gini/gini-mobile-ios pull request #755
Opened 2024-12-09 09:08 UTC by igor-gini

PP-129

2025-01-09 11:02 UTC, ValentinaIancu-Gini reviewed
@igor-gini I finished the code review for this pr. Can you please check my suggestions and questions? Thank you!

2025-01-09 11:02 UTC, ValentinaIancu-Gini commented on BankSDK/GiniBankSDKExample/GiniBankSDKExample/DemoViewController.xib
> +                <stackView opaque="NO" contentMode="scaleToFill" spacing="16" translatesAutoresizingMaskIntoConstraints="NO" id="QRX-Mq-lHn">
[clarification]Why did we not add this new option in the Settings screen? We will have more things to fix when we support landscape mode and as well in the Photo payment team we will add a new button to see the "transaction list". I would suggest moving it inside the Settings screen at the button of the screen where all the "DEbug and development options" are located.

2025-01-09 12:58 UTC, zladzeyka requested changes
@igor-gini please add also a unit test

2025-01-14 16:13 UTC, igor-gini commented on BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/GiniBankNetworkingScreenApiCoordinator.swift
> +    static var currentCoordinator: GiniBankNetworkingScreenApiCoordinator?
This needs to be at least at internal level so tests would be able to access it.

2025-01-14 16:14 UTC, igor-gini commented on BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/Networking/GiniBank+Networking.swift
> +     Aborts the current GiniBankSDK session
Sure, added

2025-01-14 16:14 UTC, igor-gini commented on BankSDK/GiniBankSDK/Sources/GiniBankSDK/Core/GiniBankNetworkingScreenApiCoordinator.swift
> +    public func closeSDK() {
I made it public, so a particular instance could be cancelled from anywhere, but I suppose it’s not actually needed, replaced it with calling finishWithCancellation directly, followed by cleaning up GiniBankConfiguration(ScreenAPICoordinator seems to be doing this in closeSreenAPIAndSendTransferSummary, so I guess we also need that here).

2025-01-14 16:35 UTC, igor-gini commented on BankSDK/GiniBankSDKExample/GiniBankSDKExample/DemoViewController.xib
> +                <stackView opaque="NO" contentMode="scaleToFill" spacing="16" translatesAutoresizingMaskIntoConstraints="NO" id="QRX-Mq-lHn">
Added a Settings item

2025-01-14 16:39 UTC, igor-gini commented
> @igor-gini please add also a unit test

I added a test, but it passes only if GiniBankAPI does not trigger preconditionFailure that there is no entitlement for access to Keychain. I added a possible solution: I made the global internal variable _GINIBANKAPILIBRARY_DISABLE_KEYCHAIN_PRECONDITION_FAILURE and set it to true in the test.

2025-01-17 09:06 UTC, zladzeyka requested changes
Thank you for the update @igor-gini 
2 tiny suggestions from my side :)

2025-01-17 09:06 UTC, zladzeyka commented on BankAPILibrary/GiniBankAPILibrary/Sources/GiniBankAPILibrary/Documents/Core/GiniBankAPI.swift
> +// should only be used in tests
[Suggestion] Please add a comment with more explanation like:

```
 /**
     Sets the default error logger. It is only used when giniErrorLoggerIsOn is true.

     - note: Internal usage only.
   */
```

2025-01-20 12:32 UTC, igor-gini commented on BankAPILibrary/GiniBankAPILibrary/Sources/GiniBankAPILibrary/Documents/Core/GiniBankAPI.swift
> +// should only be used in tests
Sure, done

2025-01-27 09:18 UTC, zladzeyka approved these changes

2025-03-03 14:13 UTC, merged